spring:
  application:
    name: gestionproyectos
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: a
    url: jdbc:h2:mem:gestiondb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
